version: 2
jobs:
  build:
    docker:
      - image: spbk/circleci-golang
    working_directory: /go/src/github.com/sunilsv/Test-Project-2013

    steps:
      - checkout

      - run: touch .env

      - run: make install
      - run: make test
      - run: make build
      - run: make package
      - run: make deploy
    